name: RDP
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract Ngrok File
      run: Expand-Archive ngrok.zip

    - name: Connect Ngrok
      run: .\ngrok\ngrok.exe config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Windows10 RDP and Initial Setup
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

        del -Force "C:\Users\Public\Desktop\Epic Games Launcher.lnk" *> out.txt 2>&1
        del -Force "C:\Users\Public\Desktop\R 4.4.1.lnk" *> out.txt 2>&1
        del -Force "C:\Users\Public\Desktop\Unity Hub.lnk" *> out.txt 2>&1 

        net config server /srvcomment:"Windows Server 2019 By lucifer" > out.txt 2>&1
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /V EnableAutoTray /T REG_DWORD /D 0 /F > out.txt 2>&1
        net user lucifer JohnCena?6969 /add >nul
        net localgroup administrators lucifer /add >nul
        net user lucifer /active:yes >nul
        net user installer /delete
        diskperf -Y >nul
        sc config Audiosrv start= auto >nul
        sc start audiosrv >nul
        ICACLS C:\Windows\Temp /grant lucifer:F >nul
        ICACLS C:\Windows\installer /grant lucifer:F >nul
        echo Successfully installed! If RDP is dead, rebuild again.
        echo IP:
        tasklist | find /i "ngrok.exe" >Nul && curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url || echo "Failed to retreive NGROK authtoken"
        echo Username: lucifer
        echo Password: JohnCena?6969
        echo You can login now
        ping -n 10 127.0.0.1 >nul

    - name: Tunnel and RDP Loop
      run: |
        Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region in 3389"'
        echo RDP CREATION SUCCESSFULL! 
    
        try {
            $processes = tasklist /fi "imagename eq ngrok.exe" | Out-String 
            if ($processes -match "ngrok.exe") {
                # ngrok.exe is running, proceed with the curl command
                curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url 
            } else {
                Write-Error "ngrok.exe not found." 
            }
        } catch {
            Write-Error "An error occurred while checking for ngrok.exe: $($_.Exception.Message)"
        }
    
        echo RDP Will be active for 6 hours and . will be printed as active indicator
        :check
        ping 127.0.0.1 > null
        cls
        goto check
